name: CI Benchmarks

on: push
  # push:
    # branches:
    #   - master

env:
  CARGO_TERM_COLOR: always

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write

# cancel in-progress job when a new push is performed
concurrency:
  group: ci-bench-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  benchmark:
    name: Performance benchmarks

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    # From: https://github.com/actions/cache/blob/main/examples.md#rust---cargo
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Run benchmark
      run: |
        cd examples
        ./run_benchmarks.sh
        cd ..


    - name: Publish benchmark result
      uses: benchmark-action/github-action-benchmark@v1
      with:
        name: Benchmarks
        tool: 'customSmallerIsBetter'
        output-file-path: examples/benchmark_results.json
        # Access token to deploy GitHub Pages branch
        github-token: ${{ secrets.GITHUB_TOKEN }}
        # Push and deploy GitHub pages branch automatically
        auto-push: true
